I want to do some experiments and play around with tensor concepts. The examples are based on the video series "Tensors For Beginners" bei eigenchris:  
https://www.youtube.com/watch?v=8ptMTLzV4-I&list=PLJHszsWbB6hrkmmq57lX8BV-o-YIOFsiG  
We represent our tensors as numpy arrays. We start by defining our old and new basis vectors, like here:  
https://www.youtube.com/watch?v=sdCmW5N1LW4&t=0m35s

In [33]:
import numpy as np

e1  = np.array([1, 0])      # 1st basis vector in old basis
e2  = np.array([0, 1])      # 2nd basis vector in old basis
et1 = np.array([2, 1])      # 1st new basis vector (t for tilde)
et2 = np.array([-1/2, 1/4]) # 2nd new basis vector
e1, e2, et1, et2

(array([1, 0]), array([0, 1]), array([2, 1]), array([-0.5 ,  0.25]))

We define a function that takes two vectors as inputs and creates a matrix from them by writing the vectors as columns into the matrix. Then we use that function to define the forward transform matrix $F$ and we also define the backward transform matrix $B$. Note that the matrix given in the video above is wrong (transposed) - chris corrected himslef later in a follow up video (https://www.youtube.com/watch?v=ipRrCPvftTk). 

In [34]:
def vecs2mat(col1, col2):
    return np.matrix([ [col1[0], col2[0]], [col1[1], col2[1]] ])

F = vecs2mat(et1, et2)              # forward transform matrix
B = np.matrix([[1/4, 1/2],[-1, 2]]) # backward transform matrix
print(F); print(B)

[[ 2.   -0.5 ]
 [ 1.    0.25]]
[[ 0.25  0.5 ]
 [-1.    2.  ]]


The columns of the forward transform matrix $F$ are the vectors onto which the 1st and 2nd unit vector $(1, 0)^T$ and $(0, 1)^T$ get mapped, which happen to coincide with our first basis vectors (i.e. our first basis was chosen to be the canonical basis of $\mathbb{R}^2$). 
<!--
But that doesn't have to be the case. In general $F_{ij}$ tells, how much of $\vec{e_i}$ is in $\tilde{\vec{e_j}}$ [verify, if that's true]
https://www.youtube.com/watch?v=ipRrCPvftTk&t=47s
-->
The given backward transform matrix $B$ is actually the inverse matrix of $F$. Let's verify this:

In [35]:
print(np.linalg.inv(F))

[[ 0.25  0.5 ]
 [-1.    2.  ]]


What that means is that if we matrix-multiply $F$ and $B$, we will get the identity matrix: $F B = B F = E$

In [37]:
print(F.dot(B)); print(B.dot(F))

[[ 1.  0.]
 [ 0.  1.]]
[[ 1.  0.]
 [ 0.  1.]]
